# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Project CI/CD Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    services:
      mysql_server:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Show all services
      env:
        MYSQL_PWD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
           docker ps

    - name: Set database info to application
      env:
        SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_PASSWORD }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_USER }}
      run: |
          sed -i 's/spring.datasource.password=.*/spring.datasource.password=${{ secrets.DATABASE_PASSWORD }}/' src/main/resources/application.properties
          sed -i 's/spring.datasource.username=.*/spring.datasource.username=${{ secrets.DATABASE_USER }}/' src/main/resources/application.properties
          sed -i 's/spring.jpa.show-sql=true/spring.jpa.show-sql=false/' src/main/resources/application.properties
          sed -i 's/spring.datasource.url=.*/spring.datasource.url=jdbc:mysql:\/\/localhost:3306\/mysqlbase/' src/main/resources/application.properties

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build with Maven
      run: mvn clean install
